"""add rss feeds and entries tables

Revision ID: 5602caca604a
Revises: ae7510620b08
Create Date: 2026-05-14 00:40:28.077982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5602caca604a'
down_revision: Union[str, None] = 'ae7510620b08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rss_feeds',
    sa.Column('kb_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('feed_type', sa.Enum('rss', 'atom', name='feedtype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('poll_interval', sa.Integer(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('last_fetch_status', sa.Enum('success', 'partial', 'failed', name='fetchstatus'), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('total_fetched', sa.Integer(), nullable=False),
    sa.Column('filter_keywords', sa.JSON(), nullable=True),
    sa.Column('filter_authors', sa.JSON(), nullable=True),
    sa.Column('filter_categories', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rss_entries',
    sa.Column('feed_id', sa.Uuid(), nullable=False),
    sa.Column('kb_id', sa.Uuid(), nullable=False),
    sa.Column('guid', sa.String(length=1000), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('new', 'ingesting', 'completed', 'filtered', 'failed', name='entrystatus'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['rss_feeds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rss_entries')
    op.drop_table('rss_feeds')
    # ### end Alembic commands ###
