"""add generated_docs table

Revision ID: a625e95516e3
Revises: 5602caca604a
Create Date: 2026-05-14 00:52:27.630330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a625e95516e3'
down_revision: Union[str, None] = '5602caca604a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_docs',
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('kb_ids', sa.JSON(), nullable=True),
    sa.Column('referenced_page_ids', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('generating', 'completed', 'failed', name='docstatus'), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('token_usage', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generated_docs')
    # ### end Alembic commands ###
